# Generated by Django 3.2.6 on 2021-08-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20190323_0543'),
        ('fcuser', '0003_auto_20200923_1234'),
    ]

    operations = [
    ]
